#!/usr/bin/python

# For Google Code Hosting.
import gdata.projecthosting.client
import gdata.projecthosting.data
import gdata.gauth
import gdata.client
import gdata.data
import atom.http_core
import atom.core

# For everything else.
import sys
import re
import string
import xml.sax
import xml.sax.handler

def main():
  print "Hello, world!"

if __name__ == '__main__':
  main()
